// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfzO6fWZLYAViE1r5LlMgNyqsXDX8wS-I',
    appId: '1:191269809993:web:c893f56f11263c88157498',
    messagingSenderId: '191269809993',
    projectId: 'ideanest-2026',
    authDomain: 'ideanest-2026.firebaseapp.com',
    storageBucket: 'ideanest-2026.firebasestorage.app',
    measurementId: 'G-LXL79S6TT4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfzO6fWZLYAViE1r5LlMgNyqsXDX8wS-I',
    appId: '1:191269809993:web:ffd0b65fe403ed7a157498',
    messagingSenderId: '191269809993',
    projectId: 'ideanest-2026',
    authDomain: 'ideanest-2026.firebaseapp.com',
    storageBucket: 'ideanest-2026.firebasestorage.app',
    measurementId: 'G-HGPPDV4YNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLk8cb0I5uLMMxVUW7toQm_5ovPjLdpjU',
    appId: '1:191269809993:android:62e07e81344fbb42157498',
    messagingSenderId: '191269809993',
    projectId: 'ideanest-2026',
    storageBucket: 'ideanest-2026.firebasestorage.app',
  );

}